spring.application.name=backend

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/docmanager
spring.datasource.username=postgres
spring.datasource.password=anas
spring.jpa.hibernate.ddl-auto=none

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Configuration du tlchargement de fichiers
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# JWT Configuration (extraites du code)
jwt.secret=anassecretkeyanassecretkeyanassecretkey
jwt.expiration=86400000

# SFTP Configuration
sftp.username=sftpuser
sftp.password=P@ssw0rd123
sftp.host=localhost
sftp.port=22

# Rpertoire de stockage des fichiers sur le serveur SFTP
sftp.upload.directory=/upload
